baseURL = "https://blairperry.netlify.com"
languageCode = "en-us"
title = "Blair Perry"
theme = "avicenna"
googleAnalytics = "UA-141897273-2"
timeout=3000
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]


[params]
  subtitle= "Evolutionary and Functional Genomics"
  interests="Evolutionary, Comparative, and Functional Genomics"
  #cv_name= ""
  blog="https://scholar.google.com/citations?user=d8A1zCEAAAAJ&hl=en" # actually google scholar link now

[[params.affilation]]
  name = "The Castoe Lab @ The University of Texas Arlington"
  position = "PhD Candidate"
  contact = "blair.perry[at]uta.edu"

#[[params.social]]
#  name = "GitHub"
#  icon = "github"
#  url = "https://github.com/hadisinaee"

[[params.social]]
  name = "Twitter"
  icon = "twitter"
  url = "https://twitter.com/blairperry614"


[[params.introduction.paragraph]]
  text="""Hello! I am a PhD candidate in the [Castoe Lab](http://www.castoelaboratory.org/) using comparative functional genomics to study the evolution and regulation of vertebrate adaptations.
   """


[[params.projects]]
	[[params.projects.project]]
		name = "Functional genomics of physiological adaptations"
		# description  = ""
		# project_page = ""
		# code_link = ""
		# blog_link = ""

  [[params.projects.project]]
    name = "Evolution and regulation of venom systems"
    # description  = ""
		# project_page = ""
		# code_link = ""
		# blog_link = ""

  [[params.projects.project]]
    name = "Comparative genome structure and function in vertebrates"
    # description  = ""
		# project_page = ""
		# code_link = ""
		# blog_link = ""

  [[params.projects.project]]
    name = "Evolution of gene regulatory machinery and networks"
    # description  = ""
		# project_page = ""
		# code_link = ""
		# blog_link = ""


[[params.publications]]
  year="2021"

  [[params.publications.paper]]
		name = "Population genomic analyses confirm male-biased mutation rates in snakes"
		authors = "Schield, D.R., __B.W. Perry__, Z.L. Nikolakis, S.P. Mackessy, and T.A. Castoe"
		dest  = "Accepted at _Journal of Heredity_"
		link = "https://academic.oup.com/jhered/advance-article/doi/10.1093/jhered/esab005/6121357?guestAccessKey=704347b7-d3b7-42c7-b443-2fb53b352977"
		code_link = ""
		blog_link = ""

  [[params.publications.paper]]
		name = "Patterns of transmission, relatedness, and genetic diversity inferred from whole genome sequencing of archival blood fluke miracidia (_Schistosoma japonicum_)"
		authors = "Nikolakis, Z.L., N.R. Hales, __B.W. Perry__, D.R. Schield, L.E. Timm, Y., Liu, B. Zhong, K.J. Kechris, D.D. Pollock, E. Carlton, and T.A. Castoe"
		dest  = "_PLoS Neglected Tropical Diseases_"
		link = "https://journals.plos.org/plosntds/article?id=10.1371/journal.pntd.0009020"
		code_link = ""
		blog_link = ""

[[params.publications]]
  year="2020"

  [[params.publications.paper]]
		name = "Physiological demands and signaling associated with snake venom production and storage illustrated by transcriptional analyses of venom glands"
		authors = "__Perry, B.W.__, D.R. Schield, A.K. Westfall, S.P. Mackessy, & T.A. Castoe"
		dest  = "_Scientific Reports_"
		link = "https://www.nature.com/articles/s41598-020-75048-y"
		code_link = ""
		blog_link = ""

  [[params.publications.paper]]
		name = "Microchromosomes exhibit distinct features of vertebrate chromosome structure and function with underappreciated ramifications for genome evolution"
		authors = "__Perry, B.W.__, D.R. Schield, R.H. Adams, & T.A. Castoe."
		dest  = "_Molecular Biology and Evolution_"
		link = "https://academic.oup.com/mbe/advance-article/doi/10.1093/molbev/msaa253/5912540"
		code_link = ""
		blog_link = ""

  [[params.publications.paper]]
		name = "Evolutionary origins of the SARC-CoV-2 sarbecovirus lineage responsible for the COVID-19 pandemic"
		authors = "Boni, M.F., P. Lemey, X. Jiang, T. Tsan-Yuk Lam, __B.W. Perry__, T.A. Castoe, A. Rambout, and D.L. Robinson."
		dest  = "_Nature Microbiology_"
		link = "https://www.nature.com/articles/s41564-020-0771-4"
		code_link = ""
		blog_link = ""

  [[params.publications.paper]]
    name = "Viral CpG deficiency provides no evidence that dogs were intermediate hosts for SARS-CoV-2"
    authors = "Pollock, D.D., T.A. Castoe, __B.W. Perry__, S. Lytras, K. Wade, D.L. Robertson, E.C. Holmes, M.F. Boni, S.L. Kosakovsky Pond, R. Parry, E.J. Carlton, J. Wood, P.S. Pennings, & R.A. Goldstein"
    dest  = "_Molecular Biology and Evolution_"
    link = "https://academic.oup.com/mbe/article/doi/10.1093/molbev/msaa178/5870838"
    code_link = ""
    blog_link = ""

  [[params.publications.paper]]
    name = "Discovery and characterization of New Delhi metallo-β-lactamase-1 inhibitor peptides that potentiate meropenem-dependent killing of carbapenemase-producing _Enterobacteriaceae_"
    authors = "Kazi, M.I., __B.W. Perry__, D.C. Card, R.D. Schargel, H.B. Ali, V.C. Obuekwe, M. Sapkota, K.N. Kang, M.W. Pellegrino, D.E. Greenberg, T.A. Castoe, & J.M. Boll"
    dest  = "_Journal of Antimicrobial Chemotherapy_"
    link = "https://academic.oup.com/jac/article-abstract/doi/10.1093/jac/dkaa242/5863537"
    code_link = ""
    blog_link = ""

  [[params.publications.paper]]
		name = "Vertebrate lineages exhibit diverse patterns of transposable element regulation and expression across tissues"
		authors = "Pasquesi,G.I.M., __B.W. Perry__, R.P. Ruggiero, M.W. Vandewege, D.R. Schield, and T.A. Castoe"
		dest  = "_Genome Biology and Evolution_"
		link = "https://academic.oup.com/gbe/advance-article/doi/10.1093/gbe/evaa068/5818493"
		code_link = ""
		blog_link = ""

  [[params.publications.paper]]
		name = "Snake recombination landscapes are concentrated in functional regions despite PRDM9"
		authors = "Schield, D.R., G.I.M. Pasquesi, __B.W. Perry__, R.H. Adams, Z.L. Nikolakis, A.K. Westfall, R.W. Orton, J.M. Meik, S.P. Mackessy, and T.A. Castoe"
		dest  = "_Molecular Biology and Evolution_"
		link = "https://academic.oup.com/mbe/advance-article-abstract/doi/10.1093/molbev/msaa003/5700722?redirectedFrom=fulltext"
		code_link = "https://figshare.com/articles/Rattlesnake_Recombination_Maps/11283224"
		blog_link = ""

[[params.publications]]
  year="2019"

  [[params.publications.paper]]
		name = "Genomic basis of convergent island phenotypes in boa constrictors"
		authors = "Card, D.C., R.H. Adams, D.R. Schield, __B.W. Perry__, A.B. Corbin, G.I.M. Pasquesi, K. Row, J. Daza, W. Booth, C. Montgomery, S. Boback, and T.A. Castoe"
		dest  = "_Genome Biology and Evolution_. 11:3123-3143"
		link = "https://academic.oup.com/gbe/article/11/11/3123/5603307"
		code_link = ""
		blog_link = ""

  [[params.publications.paper]]
		name = "Multi-species comparisons of snakes identify coordinated signaling networks underlying post-feeding intestinal regeneration"
		authors = "__Perry, B.W.__, A.L. Andrew, A.H.M. Kamal, D.C. Card, D.R. Schield, G.I.M. Pasquesi, M.W Pellegrino, S.P. Mackessy, S.M. Chowdhury, S.M. Secor, and T.A. Castoe"
		dest  = "_Proceedings of the Royal Society of London B_. 286:20190910"
		link = "https://royalsocietypublishing.org/doi/10.1098/rspb.2019.0910"
		code_link = ""
		blog_link = ""

  [[params.publications.paper]]
		name = "Allopatric divergence and secondary contact with gene flow – a recurring theme in rattlesnake speciation"
		authors = "Schield, D.R.†, __B. W. Perry†__, R. H. Adams, D. C. Card, T. Jezkova, G. I.M. Pasquesi, Z. L. Nikolakis, K. Row, J. M. Meik, C. F. Smith, S. P. Mackessy, and T. A. Castoe (†Co-first authors)"
		dest  = "_Biological Journal of the Linnean Society_. 128:149-169"
		link = "https://academic.oup.com/biolinnean/advance-article/doi/10.1093/biolinnean/blz077/5523649"
		code_link = ""
		blog_link = ""

  [[params.publications.paper]]
		name = "The origins and evolution of chromosomes, dosage compensation, and mechanisms underlying venom regulation in snakes"
		authors = "Schield, D.R., D.C. Card, N.M. Hales, __B.W. Perry__, G.I.M. Pasquesi, H. Blackmon, R.H. Adams, A.B. Corbin, C.F. Smith, B. Ramesh, J.P. Demuth, E. Betran, M. Tollis, J.M. Meik, S.P. Mackessy and T.A. Castoe"
		dest  = "_Genome Research_. 29:590-601"
		link = "https://genome.cshlp.org/content/29/4/590"
		code_link = "https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Ffigshare.com%2Fprojects%2FPrairie_rattlesnake_Crotalus_viridis_genome_assembly_and_annotation%2F66560&data=02%7C01%7Ctodd.castoe%40uta.edu%7Cef35e8799f554ee49ba408d7104b1971%7C5cdc5b43d7be4caa8173729e3b0a62d9%7C0%7C0%7C636995787037483313&sdata=%2B6ugCboFDQReMI2OUuL%2F%2FNko2Y7uDxnpm6kDIspWGFk%3D&reserved=0"
		blog_link = ""

[[params.publications]]
  year="2018"

  [[params.publications.paper]]
		name = "Novel ecological and climatic conditions drive rapid adaptation in invasive Florida Burmese pythons"
		authors = "Card, D.C., __B.W. Perry__, R.H. Adams, D.R. Schield, A. Young, A.L. Andrew, T. Jezkova, M.R. Walsh, M. Rockford, F. Mazzotti, K. Hart, M. Hunter, and T.A. Castoe"
		dest  = "_Molecular Ecology_. 27:4744-4757"
		link = "https://onlinelibrary.wiley.com/doi/abs/10.1111/mec.14885"
		code_link = ""
		blog_link = ""

  [[params.publications.paper]]
		name = "Evolution: Plasticity versus selection, or plasticity and selection?"
		authors = "__Perry, B.W.__, D.R. Schield, and T.A. Castoe"
		dest  = "Current Biology. 28:R1104-R1106"
		link = "https://www.cell.com/current-biology/fulltext/S0960-9822(18)30980-1"
		code_link = ""
		blog_link = ""

	[[params.publications.paper]]
    name = "Molecular adaptations for sensing and securing prey, and insight into amniote genome diversity, from the garter snake genome"
    authors = "__Perry, B.W.__, D.C. Card, J.W. McGlothlin, G.I.M. Pasquesi, R.H. Adams, D.R. Schield, N.R. Hales, A.B. Corbin, J.P. Demuth, F.G. Hoffmann, M.W. Vandewege, R. Schott, N. Bhattacharyya, B.S.W. Chang, N.R. Casewell, G. Whiteley, J. Reyes-Velasco, S.P. Mackessy, T. Gamble, K.B. Storey, K.K. Biggar, C.N. Passow, C. Kuo, S.E. McGaugh, A.M. Bronikowski, J. de Koning, S.V. Edwards, M.E. Pfrender, P. Minx, E.D. Brodie III, E.D. Brodie, Jr., W.C. Warren, and T.A. Castoe"
    dest  = "_Genome Biology and Evolution_. 10:2110-2129"
    link = "https://academic.oup.com/gbe/article/10/8/2110/5061318?guestAccessKey=56ba9516-8d77-4c3d-a6df-1164c74cde38"
    code_link = ""
    blog_link = ""

	[[params.publications.paper]]
    name = "Squamate reptiles challenge paradigms of genomic repeat element evolution set by birds and mammals"
    authors = "Pasquesi, G.I.M., R.H. Adams, D.C. Card, D.R. Schield, __B.W. Perry__, A.B. Corbin, J. Reyes-Velasco, R.P. Ruggiero, M.W. Vandewege, J.A. Shortt, and T.A. Castoe"
    dest  = "_Nature Communications_. 127:669-681"
    link = "https://www.nature.com/articles/s41467-018-05279-1"
    code_link = ""
    blog_link = ""

	[[params.publications.paper]]
    name = "Cryptic genetic diversity, population structure, and gene flow in Mohave rattlesnakes (_Crotalus scutulatus_)"
    authors = "Schield, D.R, D.C. Card, R.H Adams, A.B. Corbin, T. Jezkova, N.R. Hales, J.M. Meik, __B.W. Perry__, C.L. Spencer, L.L. Smith, G. Campillo Garcia, N.M. Bouzid, J.L. Strickland, R.W. Bryson Jr., C.L. Parkinson, O. Flores-Viella, S.P. Mackessy and T.A. Castoe"
    dest  = "_Molecular Phylogenetics and Evolution_. 9:2774"
    link = "https://www.sciencedirect.com/science/article/pii/S1055790317304992?via%3Dihub"
    code_link = ""
    blog_link = ""


[[params.publications]]
  year="2017"

  [[params.publications.paper]]
		name = "Growth and stress response mechanisms underlying post-feeding regenerative organ growth in the Burmese python"
		authors = "Andrew, A.L.†, __B.W. Perry†__, D.C. Card, D.R. Schield, R.P. Ruggiero, S.E. McGaugh, A. Chowdhary, S.M. Secor, and T.A. Castoe (†Co-first authors)"
		dest  = "_BMC Genomics_. 18:338"
		link = "https://bmcgenomics.biomedcentral.com/articles/10.1186/s12864-017-3743-1"
		code_link = ""
		blog_link = ""

  [[params.publications.paper]]
		name = "Insight into the roles of selection in speciation from genomic patterns of divergence and introgression in secondary contact in venomous rattlesnakes"
		authors = "Schield, D.R., R.H. Adams, D.C. Card, __B.W. Perry__, G.I.M. Pasquesi, T. Jezkova, D.M. Portik, A.L. Andrew, C.L. Spencer, E.E. Sanchez, M.K. Fujita, S.P. Mackessy, and T.A. Castoe"
		dest  = "_Ecology and Evolution_. 7:3951-3966"
		link = "https://onlinelibrary.wiley.com/doi/abs/10.1002/ece3.2996"
		code_link = ""
		blog_link = ""



[[params.publications]]
  year="2016"

  [[params.publications.paper]]
		name = "Phylogeographic and population genetic analyses reveal multiple species of Boa and independent origins of insular dwarfism"
		authors = "Card, D.C., D.R Schield, R.H. Adams, A.B. Corbin, __B.W. Perry__, A.L. Andrew, G.I.M. Pasquesi, E.N. Smith, T. Jezkova, S.M. Boback, W. Booth, and T.A. Castoe"
		dest  = "_Molecular Phylogenetics and Evolution_. 102:104-116"
		link = "https://www.sciencedirect.com/science/article/pii/S1055790316301245?via%3Dihub"
		code_link = ""
		blog_link = ""

  [[params.publications.paper]]
		name = "No safety in the trees: Evidence of local and lineage-level adaptation of the Eastern gray squirrel (_Sciurus carolinensis_) to resisting venom of sympatric rattlesnakes"
		authors = "Pomento, A.M†, __B.W. Perry†__, R.D. Denton, H.L. Gibbs, M.L. Holding (†Co-first authors)"
		dest  = "_Toxicon_. 18:149-155"
		link = "https://www.sciencedirect.com/science/article/pii/S0041010116301295"
		code_link = ""
		blog_link = ""
